language: java
jdk:
- openjdk6
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
script: mvn deploy --settings target/travis/settings.xml
branches:
  only:
  - master
env:
  global:
  - secure: V4/Y93YIsz7WPJnjvok34x/io41rGZ7v/etlSjzScFoP3rxF6h7ejNM30mzENeZfLwVz7Y5ayoILXgLIUti3S7BX4qw0Dxdgztd2eiNEe9E8SBLZDWfwjw8YXiChBQAd3y339qynNoVqoM1Is55UyuHOPx4dOF8MO8J5G6e2BQ4=
  - secure: H+hcDQaEThZh6S9uwyBQ3nJkWvI4l8DU3z3DjEqgzrvQJ7N4dhSPB3Vwj4Mza1u9KX5fka7WuC+zdn1j+rIFvwTwwh9NTjmHHA1HL/7O1/fr1Z/qXyHF5YR8rh8cE82AC9j2SzodlnoEYhY/17jczBSs2YFRlaVm9g/oGwdCjis=
